version: '3.4'

services:
  tiendaservicios.api.libros:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6105:8080"

  tiendaservice.api.autor:
    # build:
    #   context: .
    #   dockerfile: TiendaService.Api.Autor/Dockerfile
    # volumes:
    #   - ./TiendaService.Api.Autor:/app        
    #   - ~/.nuget/packages:/root/.nuget/packages:ro 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6104:8080"

