version: '3.4'

services:
  tiendaservicios.api.libros:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapilibros
    build:
      context: .
      dockerfile: TiendaServicios.Api.Libros/Dockerfile
    networks:
      - microservicenet

  tiendaservice.api.autor:
    image: ${DOCKER_REGISTRY-}tiendaserviceapiautor
    build:
      context: .
      dockerfile: TiendaService.Api.Autor/Dockerfile
    networks:
      - microservicenet

networks:
  microservicenet:
    driver: bridge
